### ISSUE TITLE
Add heartbleed check

### ISSUE THREAD

**Issue by cybershambles** [imrehg/twbankssl#14]

**Comment by imrehg** [comment]
Added a patch to enable this in fc4f0b20ed21ef759bd5f6dd29edf43caa527404, can test it. With the current servers I'm monitoring it comes back all green, so that's not too much of a differentiation between the websites.

In general it would be good to add, though if a site is exposed, it would show up in the SSLLabs test very much (meaning: getting a very low score), so maybe it's better to use the site real estate to something more informative. At the moment  the patch is available if you want to try out, and I'll hold it back from master until the user interface is better worked out to be informative and not confusing.

Thanks!

**Comment by cybershambles** [comment]
Thanks for the patch. I am in agreement tho. It's not very important anymore as everybody seems to be scanning for this kind of thing.

I've got a list of 850 domains I'm currently scanning and the heartbleed information might catch a few domains for my list... otherwise, I'll remove it like you have.
