### ISSUE TITLE
False-negative for BEAST on www.getup.org.au

### ISSUE THREAD

**Issue by cybershambles** [imrehg/twbankssl#18]
I've scanned Get Up! - The scores show Bad for BEAST.
https://httpswatch.com.au/easteregg/index.html

yet the direct tests online pass
https://www.ssllabs.com/ssltest/analyze.html?d=www.getup.org.au

Is this a mistake?

**Comment by imrehg** [comment]
If you look further down the SSLLabs Test results page, it says "BEAST: not mitigated on server side", so it actually fails, not not being penalized.

More specifically, the Good/Bad status is coming from the [SSLLabs API endpoint details](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md#endpointdetails) whether `vulnbeast` is True/False, and the scanner just passes that on.

Even more specifically, since [BEAST is a client side vulnerability](https://community.qualys.com/blogs/securitylabs/2013/09/10/is-beast-still-a-threat?_ga=1.258833418.187053156.1426472445), it's not especially meaningful. Thus I'm planning to take that off the reports anyway, and use space for some more interesting metric.
